"""add risk_disclosure_accepted

Revision ID: 0ac409fb6741
Revises: d400d8920172
Create Date: 2026-08-12 21:38:55.857298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac409fb6741'
down_revision: Union[str, Sequence[str], None] = 'd400d8920172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('risk_disclosure_accepted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'risk_disclosure_accepted')
    # ### end Alembic commands ###
