"""add signal dropped fields

Revision ID: cfbdf6563a03
Revises: 0ac409fb6741
Create Date: 2026-08-12 23:09:13.368470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfbdf6563a03'
down_revision: Union[str, Sequence[str], None] = '0ac409fb6741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_signals', sa.Column('source_mode', sa.String(length=1), nullable=False))
    op.add_column('source_signals', sa.Column('received_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('source_signals', sa.Column('dropped', sa.Boolean(), nullable=False))
    op.add_column('source_signals', sa.Column('drop_reason', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_signals', 'drop_reason')
    op.drop_column('source_signals', 'dropped')
    op.drop_column('source_signals', 'received_at')
    op.drop_column('source_signals', 'source_mode')
    # ### end Alembic commands ###
